#!/usr/bin/env php
<?php

define('YII_DEBUG', $_SERVER['USER'] == 'fredy');
define('ROOT_DIR', __DIR__);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/config/common.php',
    require __DIR__ . '/config/console.php'
);
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);

