<?php

namespace app\models\forms;

use yii\base\Model;
use Yii;
use yii\web\UploadedFile;

class OrderForm extends Model
{

    private $_oldAttributes = [];

    public function rules() {
        return [
            [['fullname', 'country', 'birth_date', 'phone'], 'required'],
            [['order', 'product_id', 'city', 'zip_code', 'whatsapp', 'status', 'user_id'], 'safe'],
        ];
    }

    public function attributeLabels() {
        return [
            'fullname'             => Yii::t('site', 'Full name'),
            'country'               => Yii::t('site', 'Country'),
            'birth_date'            => Yii::t('site', 'Birth date'),
            'phone'                 => Yii::t('site', 'Phone'),
            'order' => 'Заказ',
            'product_id' => 'Товар',
            'city' => 'Город',
            'zip_code' => 'Индекс',
            'whatsapp' => 'WhatsApp',
            'status' => 'Статус',
        ];
    }

    public function __construct($config = []) {
        $user = Yii::$app->user->identity;
        $this->setAttributes($user->getAttributes());
        parent::__construct($config);
    }

    public function setAttributes($values, $safeOnly = true) {
        if(empty($this->_oldAttributes)){
            $this->_oldAttributes = $this->attributes;
        }
        parent::setAttributes($values, $safeOnly); // TODO: Change the autogenerated stub
    }

    public function save() {
        if($this->validate()){
            $user = Yii::$app->user->identity;
            $user->wallet = $user->wallet ?: $this->wallet;
            $user->wallet_perfect = $user->wallet_perfect ?: $this->wallet_perfect;
            $user->wallet_tether = $user->wallet_tether ?: $this->wallet_tether;
            $user->wallet_banki_rf = $user->wallet_banki_rf ?: $this->wallet_banki_rf;
            $user->wallet_dc = $user->wallet_dc ?: $this->wallet_dc;
            $user->full_name = $user->full_name ?: $this->full_name;
            $user->country = $user->country ?: $this->country;
            $user->phone = $user->phone ?: $this->phone;
            $user->birth_date = $user->birth_date ?: $this->birth_date;
            $avatar = UploadedFile::getInstance($this, 'avatar');
            if($avatar && $avatar->size && $avatar->error == 0){
                $user->avatar = file_get_contents($avatar->tempName);
                unlink($avatar->tempName);
            }
            if(!$user->save(true, ['wallet', 'wallet_perfect', 'wallet_tether', 'wallet_banki_rf', 'wallet_dc', 'full_name', 'country', 'phone', 'birth_date', 'avatar', 'updated_at'])){
                $this->addErrors($user->getErrors());
                return false;
            }
            return true;
        }
        return false;
    }

    public function save() {
        $order = new \app\models\EmeraldOrder();
        $order->id_user = $this->id_user;
        $order->fullname = $this->fullname;
        $order->country = $this->country;
        $order->birth_date = $this->birth_date;
        $order->phone = $this->phone;
        $order->order = 'Пластырь';
        $order->product_id = 1;
        $order->city = $this->city;
        $order->zip_code = $this->zip_code;
        $order->whatsapp = $this->whatsapp;
        $order->status = $this->status;
        if ($order->save) return true;

        return false;
    }
}