<?php

namespace app\models\forms;

use yii\base\Model;
use Yii;
use yii\web\UploadedFile;

class ProfileForm extends Model
{

    public $wallet;
    public $wallet_perfect;
    public $wallet_tether;
    public $wallet_banki_rf;
    public $wallet_dc;
    public $full_name;
    public $country;
    public $birth_date;
    public $phone;
    public $avatar;

    private $_oldAttributes = [];

    public function rules() {
        return [
            [['full_name', 'country', 'birth_date', 'phone'], 'required'],
            ['wallet', 'validatePayeer', 'skipOnEmpty' => false, 'skipOnError' => false],
            ['wallet_perfect', 'validatePerfect', 'skipOnEmpty' => false, 'skipOnError' => false],
            ['wallet_tether', 'validateTether', 'skipOnEmpty' => false, 'skipOnError' => false],
            ['wallet_banki_rf', 'validateBankiRf', 'skipOnEmpty' => false, 'skipOnError' => false],
            ['wallet_dc', 'validateDC', 'skipOnEmpty' => false, 'skipOnError' => false],
            [['wallet'], 'match', 'pattern' => '#[P|U][0-9]+#sm'],
            [['avatar'], 'safe'],
        ];
    }

    public function validatePerfect($attribute, $params)
    {
        if (!$this->wallet || !$this->wallet_tether || !$this->wallet_banki_rf || !$this->wallet_dc) {
            return;
        }
        $this->addError($attribute, 'Not empty');
    }
    public function validatePayeer($attribute, $params)
    {
        if (!$this->wallet_perfect || !$this->wallet_tether || !$this->wallet_banki_rf || !$this->wallet_dc) {
            return;
        }
        $this->addError($attribute, 'Not empty');
    }
    public function validateTether($attribute, $params)
    {
        if (!$this->wallet_perfect || !$this->wallet || !$this->wallet_banki_rf || !$this->wallet_dc) {
            return;
        }
        $this->addError($attribute, 'Not empty');
    }
    public function validateBankiRf($attribute, $params)
    {
        if (!$this->wallet_perfect || !$this->wallet || !$this->wallet_tether || !$this->wallet_dc) {
            return;
        }
        $this->addError($attribute, 'Not empty');
    }
    public function validateDC($attribute, $params)
    {
        if (!$this->wallet_perfect || !$this->wallet || !$this->wallet_tether || !$this->wallet_banki_rf) {
            return;
        }
        $this->addError($attribute, 'Not empty');
    }

    public function attributeLabels() {
        return [
            'wallet'                => Yii::t('site', 'Wallet'),
            'wallet_perfect'        => Yii::t('site', 'Wallet Perfect'),
            'wallet_tether'         => Yii::t('site', 'Wallet Tether'),
            'wallet_banki_rf'       => Yii::t('site', 'Wallet Banki RF'),
            'wallet_dc'             => Yii::t('site', 'Wallet DC'),
            'full_name'             => Yii::t('site', 'Full name'),
            'country'               => Yii::t('site', 'Country'),
            'birth_date'            => Yii::t('site', 'Birth date'),
            'phone'                 => Yii::t('site', 'Phone'),
            'avatar'                => Yii::t('site', 'Avatar'),
        ];
    }

    public function __construct($config = []) {
        $user = Yii::$app->user->identity;
        $this->setAttributes($user->getAttributes());
        parent::__construct($config);
    }

    public function setAttributes($values, $safeOnly = true) {
        if(empty($this->_oldAttributes)){
            $this->_oldAttributes = $this->attributes;
        }
        parent::setAttributes($values, $safeOnly); // TODO: Change the autogenerated stub
    }

    public function save() {
        if($this->validate()){
            $user = Yii::$app->user->identity;
            $user->wallet = $user->wallet ?: $this->wallet;
            $user->wallet_perfect = $user->wallet_perfect ?: $this->wallet_perfect;
            $user->wallet_tether = $user->wallet_tether ?: $this->wallet_tether;
            $user->wallet_banki_rf = $user->wallet_banki_rf ?: $this->wallet_banki_rf;
            $user->wallet_dc = $user->wallet_dc ?: $this->wallet_dc;
            $user->full_name = $user->full_name ?: $this->full_name;
            $user->country = $user->country ?: $this->country;
            $user->phone = $user->phone ?: $this->phone;
            $user->birth_date = $user->birth_date ?: $this->birth_date;
            $avatar = UploadedFile::getInstance($this, 'avatar');
            if($avatar && $avatar->size && $avatar->error == 0){
                $user->avatar = file_get_contents($avatar->tempName);
                unlink($avatar->tempName);
            }
            if(!$user->save(true, ['wallet', 'wallet_perfect', 'wallet_tether', 'wallet_banki_rf', 'wallet_dc', 'full_name', 'country', 'phone', 'birth_date', 'avatar', 'updated_at'])){
                $this->addErrors($user->getErrors());
                return false;
            }
            return true;
        }
        return false;
    }
}